package zhonger.cancer.bbs.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import zhonger.cancer.bbs.model.UserLike;
import zhonger.cancer.bbs.model.UserLikeExample;
@Mapper
public interface UserLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlike
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    long countByExample(UserLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlike
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    int deleteByExample(UserLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlike
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlike
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    int insert(UserLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlike
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    int insertSelective(UserLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlike
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    List<UserLike> selectByExampleWithRowbounds(UserLikeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlike
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    List<UserLike> selectByExample(UserLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlike
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    UserLike selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlike
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    int updateByExampleSelective(@Param("record") UserLike record, @Param("example") UserLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlike
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    int updateByExample(@Param("record") UserLike record, @Param("example") UserLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlike
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    int updateByPrimaryKeySelective(UserLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlike
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    int updateByPrimaryKey(UserLike record);
}