package zhonger.cancer.bbs.model;

public class UserLike {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlike.id
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlike.ACCOUNT_ID
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlike.NAME
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlike.galgame
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    private Integer galgame;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlike.animation
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    private Integer animation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlike.fantasy
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    private Integer fantasy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlike.imaginary
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    private Integer imaginary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlike.blood
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    private Integer blood;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlike.cute
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    private Integer cute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlike.lachrymatory
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    private Integer lachrymatory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlike.crossing
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    private Integer crossing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlike.campus
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    private Integer campus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlike.comedy
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    private Integer comedy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlike.matory
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    private Integer matory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlike.battle
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    private Integer battle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlike.magic
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    private Integer magic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlike.id
     *
     * @return the value of userlike.id
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlike.id
     *
     * @param id the value for userlike.id
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlike.ACCOUNT_ID
     *
     * @return the value of userlike.ACCOUNT_ID
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlike.ACCOUNT_ID
     *
     * @param accountId the value for userlike.ACCOUNT_ID
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlike.NAME
     *
     * @return the value of userlike.NAME
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlike.NAME
     *
     * @param name the value for userlike.NAME
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlike.galgame
     *
     * @return the value of userlike.galgame
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public Integer getGalgame() {
        return galgame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlike.galgame
     *
     * @param galgame the value for userlike.galgame
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public void setGalgame(Integer galgame) {
        this.galgame = galgame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlike.animation
     *
     * @return the value of userlike.animation
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public Integer getAnimation() {
        return animation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlike.animation
     *
     * @param animation the value for userlike.animation
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public void setAnimation(Integer animation) {
        this.animation = animation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlike.fantasy
     *
     * @return the value of userlike.fantasy
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public Integer getFantasy() {
        return fantasy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlike.fantasy
     *
     * @param fantasy the value for userlike.fantasy
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public void setFantasy(Integer fantasy) {
        this.fantasy = fantasy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlike.imaginary
     *
     * @return the value of userlike.imaginary
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public Integer getImaginary() {
        return imaginary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlike.imaginary
     *
     * @param imaginary the value for userlike.imaginary
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public void setImaginary(Integer imaginary) {
        this.imaginary = imaginary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlike.blood
     *
     * @return the value of userlike.blood
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public Integer getBlood() {
        return blood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlike.blood
     *
     * @param blood the value for userlike.blood
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public void setBlood(Integer blood) {
        this.blood = blood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlike.cute
     *
     * @return the value of userlike.cute
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public Integer getCute() {
        return cute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlike.cute
     *
     * @param cute the value for userlike.cute
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public void setCute(Integer cute) {
        this.cute = cute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlike.lachrymatory
     *
     * @return the value of userlike.lachrymatory
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public Integer getLachrymatory() {
        return lachrymatory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlike.lachrymatory
     *
     * @param lachrymatory the value for userlike.lachrymatory
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public void setLachrymatory(Integer lachrymatory) {
        this.lachrymatory = lachrymatory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlike.crossing
     *
     * @return the value of userlike.crossing
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public Integer getCrossing() {
        return crossing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlike.crossing
     *
     * @param crossing the value for userlike.crossing
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public void setCrossing(Integer crossing) {
        this.crossing = crossing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlike.campus
     *
     * @return the value of userlike.campus
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public Integer getCampus() {
        return campus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlike.campus
     *
     * @param campus the value for userlike.campus
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public void setCampus(Integer campus) {
        this.campus = campus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlike.comedy
     *
     * @return the value of userlike.comedy
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public Integer getComedy() {
        return comedy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlike.comedy
     *
     * @param comedy the value for userlike.comedy
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public void setComedy(Integer comedy) {
        this.comedy = comedy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlike.matory
     *
     * @return the value of userlike.matory
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public Integer getMatory() {
        return matory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlike.matory
     *
     * @param matory the value for userlike.matory
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public void setMatory(Integer matory) {
        this.matory = matory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlike.battle
     *
     * @return the value of userlike.battle
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public Integer getBattle() {
        return battle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlike.battle
     *
     * @param battle the value for userlike.battle
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public void setBattle(Integer battle) {
        this.battle = battle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlike.magic
     *
     * @return the value of userlike.magic
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public Integer getMagic() {
        return magic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlike.magic
     *
     * @param magic the value for userlike.magic
     *
     * @mbg.generated Mon Apr 19 13:47:30 CST 2021
     */
    public void setMagic(Integer magic) {
        this.magic = magic;
    }
}